// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:zero/data/models/fasting_session_model.dart';
import 'package:zero/data/models/journal_entry_model.dart';
import 'package:zero/data/models/user_model.dart';
import 'package:zero/data/models/water_intake_model.dart';
import 'package:zero/data/models/weight_entry_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(FastingSessionAdapter());
    registerAdapter(JournalEntryAdapter());
    registerAdapter(UserModelAdapter());
    registerAdapter(WaterIntakeAdapter());
    registerAdapter(WeightEntryAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(FastingSessionAdapter());
    registerAdapter(JournalEntryAdapter());
    registerAdapter(UserModelAdapter());
    registerAdapter(WaterIntakeAdapter());
    registerAdapter(WeightEntryAdapter());
  }
}
